variables:
  ARM_PASS: $(adminpass)

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: CopyFiles@2
  inputs:
    #SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
    SourceFolder: 'quickstarts/microsoft.web/web-app-asp-app-on-asev2-create/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azuredeploycon'
    #azureSubscription: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'tim-rg'
    #resourceGroupName: 'ARMPipelinesLAMP-rg'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName $(siteName) -appServicePlanName $(appServicePlanName) -appServiceEnvironmentName $(appServiceEnvironmentName)'
    #overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'
